name: dartnate
description: Package for new project dartnate
version: 0.0.31
repository: https://github.com/mouratocarlos/dartnate

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  postgres: ^2.4.3
  mysql1: ^0.20.0
  yaml: ^3.1.1