name: dartnate
description: Package for new project dartnate
version: 0.0.6
repository: https://github.com/mouratocarlos/dartnate

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  postgres: ^2.4.3